### PR TITLE
bugfix: namespaces do not marking as used variables

### PR DESCRIPTION
**Pull request by SergeyPugachyov**

### CODE REVIEW

**Comment by SergeyPugachyov** [comment]
For example:
```
      DECLARE qsp NAMESPACE  'http://www.ww.ru/types/QSP';
      SET OutputRoot.XMLNSC.qsp:Request = '';
```

Test UnusedVariableCheckTest failed on variable "qsp"

**Comment by ThomasPohl** [comment]
Hi @SergeyPugachyov,
thanks for your pull request. You are right thats a bug. Before I'll add your changes, can you please look at the failing tests?
Tests in error: 
  HighlightSymbolTableBuilderTest.sonar_symbol_table:71->EsqlTreeModelTest.context:113 » NullPointer
  HighlightSymbolTableBuilderTest.byte_order_mark_should_not_increment_offset:88->EsqlTreeModelTest.context:113 » NullPointer
  RoutineTypeTest.setUp:32->TypeTest.setUp:41 » NullPointer
  RoutineTypeTest.setUp:32->TypeTest.setUp:41 » NullPointer
  RoutineTypeTest.setUp:32->TypeTest.setUp:41 » NullPointer

**Comment by SergeyPugachyov** [comment]
Hi @ThomasPohl ,
Sorry, I forgot to run tests. I'm added changes

**Comment by ThomasPohl** [comment]
@SergeyPugachyov I merged you changes into develop and will add them to the next release. Thanks for your input

**Pull request merged**
